version: '3'
services:
  backend:
    build: ./backend
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    depends_on:
      - mysql-db
    networks:
      - backend
  mysql-db:
    image: mysql:8.0.33
    ports:
      - '13306:3306'
    expose:
      - 13306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: freshemy
    volumes:
      - ./backend/prisma/data:/var/lib/mysql
    networks:
      - backend


volumes:
  mysql: ~
networks:
  backend:
    driver: bridge



